language: node_js 
node_js: node 
sudo: required 
before_install: 
  - npm install -g node-gyp 
env: 
  - CXX=g++-4.8 
addons: 
  apt: 
   sources: 
    - ubuntu-toolchain-r-test 
   packages: 
    - gcc-4.8 
    - g++-4.8
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: DBC13VK0xL3La++5jj+DymKP3GbOXHNuEIAI1vg7tV8iHTT/6STsJqZ6XBHD4c0QnkCV+Tr1zPmx+GnzTlTLPl3NMKgpurGr7dZPDkYWd2Inhx1wP46/9qLTe3ydpGoAlqISeFC2w58nKy8SX55W57EKod0yIxgJY/uW4IE7hn01FM5lpr3dxKdcvb00Q/mLX9G1VbAtGl2z6hMObaQkENbrHgvVdB8QYFH2/CXqgE1Ddqg96g4JuSu7muER1fonq8HNwKqFdHpOObepYvRNaaprR7YEF4oW9cncDdlNBZX+Cyzh0EBeD9idpsCGdLjLRFep6MG+HFSTS0PvH9wuFd2CfcSBFMA+ZB3mFS8w1Cxw1r61yJhhSPGj+L3/BIcVLb0N10x2w9WVpT3E2fsuqtIggU/dkgdLFBRVReWhkB/HFqwDTAWSaVXamo6njbjspotCNDgAAt7zdgy7Z7rFpVy6/+0RgKr4ta67zgVF1WW8toxHfQegczIi5jm5q5mBG3B/Cgo/e8mhq+j55GAXFyJCqQjZs7zAOzZ4t4tvTKlcc9hEOgX7KXlaXqyY02tf89yZkaQQ4PzgZ98BJhc1Hs3/bkXahlBMa+pUbPtOq7iXAqxKjS+a1ae5wUlPkQGMbx0CMIcLnyatWHC+Gpe0FEXW+sZ2WFkH1x7s+ZEDyGc=
  app: shrouded-ocean-80561
  on:
    repo: bernadettekelly/collaboration-space