language: node_js 
node_js: node 
sudo: required 
before_install: 
  - npm install -g node-gyp 
env: 
  - CXX=g++-4.8 
addons: 
  apt: 
   sources: 
    - ubuntu-toolchain-r-test 
   packages: 
    - gcc-4.8 
    - g++-4.8
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: VnV8MQZduImy7CvwGxibtMNrqExFOWJJHiG+rdMdHvAnzFYxflXQkpSb8c79VWAD17J4NUT31xHCeiusGrFSh+gvrY4NUyKgCZJbruk3YJPvlKazXQElrtxIIg4dIKEvD2OSHUJOKGjJCnMzi5QRO1jGDrlWOpa+rhtQomLRsUqITzYgLKRcaNPY4oQYYCDYZ3XBpGtxleDKYrsL5CXYjOiQsYGMMSq1jwVycjBIu6pHqA5AfAnZ6CwBQLsN+c7KaascnetA/XmxJIsIBP+vMOGZyGapv/R14T+CrmJzMQYzCib3g/B2fvJ38FPgr0GQgxvH3JOlZM07NHTwjlzA+KPMM3Km7SrRRIuAPR8bY6N9iimhRfZjO5CwVoTjwJVG8pC41B0dz63G/JCy/lruy8OM5vysYX+kf9kaj9le2+iQTERpoaxlB/u6W4V0yy84J1u9f4c0BIsko09LSamzpbHgBhrHo1qJFOOWkQN+8PDWvz9ucTALe3Izc6SviXJVNYY4OOFixa5EYUgW0+NAzulC2nOtj9O6PY23Its12hCIoAcfaId2TYa6z1TGMfmZh/DssvLJEmH7ax4CGPHX2nXZwWqp+ooaX+IXU5ClaDI/pqfzmtih35ybafMKZPzSSIvGN/Sl2rRJ5YUC2PB6/H6R939gNiFzvifNgiDKutE=
  app: shrouded-ocean-80561
  on:
    repo: bernadettekelly/collaboration-space